name: Local Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-express-app .

      - name: Stop old container
        run: docker stop my-express-app || true

      - name: Remove old container
        run: docker rm my-express-app || true

      - name: Run container
        run: docker run -d -p 8080:8080 --name my-express-app my-express-app